pom.xml, src/main/java/com/foodietime/cart/model/CartVO.java, src/main/java/com/foodietime/orddet/model/OrdDetVO.java, src/main/java/com/foodietime/orders/model/OrdersVO.java, src/main/resources/application.properties
=> fix: fix SQL  password

src/main/java/com/foodietime/memfavlist/model/FavoriteListRepository.java, src/main/java/com/foodietime/memfavlist/model/FavoriteListService.java, src/main/java/com/foodietime/product/model/ProductCategoryRepository.java, src/main/java/com/foodietime/product/model/ProductCategoryService.java
=> feat:create ProductCategoryRepository、ProductCategoryService

src/main/java/com/foodietime/product/controller/ProductCategoryController.java, src/main/java/com/foodietime/product/controller/ProductController.java, src/main/java/com/foodietime/product/model/ProductService.java, src/main/java/com/foodietime/product/model/ProductVO.java
=> feat:ProductService、ProductController

src/main/resources/templates/admin/test.html
=> modify: add folder

src/main/java/com/foodietime/cart/model/CartVO.java, src/main/java/com/foodietime/groupbuyingcollectionlist/controller/GroupBuyingCollectionListController.java, src/main/java/com/foodietime/orddet/model/OrdDetVO.java, src/main/java/com/foodietime/orders/model/OrdersVO.java, src/main/java/com/foodietime/product/model/ProductVO.java
=> fix: fix name

src/main/java/com/foodietime/cart/controller/CartController.java, src/main/java/com/foodietime/cart/model/CartRepository.java, src/main/java/com/foodietime/cart/model/CartService.java, src/main/resources/static/css/common/style.css, src/main/resources/static/css/front/cart/cart.css, src/main/resources/templates/front/cart/cart.html, src/main/resources/templates/front/cart/checkout.html
=> modify: add new Cart

src/main/java/com/foodietime/act/model/ActRepository.java, src/main/java/com/foodietime/act/model/ActService.java, src/main/java/com/foodietime/act/model/ActVO.java, src/main/java/com/foodietime/act/model/controller/ActController.java, src/main/java/com/foodietime/store/controller/PageController.java, src/main/java/com/foodietime/store/model/StoreVO.java, src/main/resources/templates/front/store/store_coupon_prodphoto.html, src/main/resources/templates/front/store/store_edit2.html
@DateTimeFormat(pattern = "HH:mm")
=> fix StoreVO NotEmpty 改成 NotNull. 10 .11 改  LocalTime

src/main/java/com/foodietime/post/controller/PostController.java, src/main/java/com/foodietime/post/model/PostRepository.java, src/main/java/com/foodietime/post/model/PostService.java, src/main/java/com/foodietime/post/model/PostVO.java, src/main/java/com/foodietime/reportpost/controller/ReportPostController.java, src/main/java/com/foodietime/reportpost/model/ReportPostRepository.java, src/main/java/com/foodietime/reportpost/model/ReportPostService.java
Feat : 新增reportpost.controller
=> Modify :修改post

src/main/java/com/foodietime/cart/controller/CartController.java, src/main/java/com/foodietime/cart/model/CartRepository.java, src/main/java/com/foodietime/cart/model/CartService.java, src/main/resources/static/css/front/cart/cart.css, src/main/resources/static/js/front/cart/cart.js, src/main/resources/templates/front/cart/cart.html, src/main/resources/templates/index.html
[modify: fix cart part and CartController.java](https://github.com/taneess7/CJA101_G5_FoodieTime/commit/9538246a778e0843d7c8c992166b51b4144e2612)
[modify: chang index.html to Thymeleaf](https://github.com/taneess7/CJA101_G5_FoodieTime/commit/cdc84d55e5ade3c14df4a6e5bf64a38265033346)
[modify: add method to CartService.java](https://github.com/taneess7/CJA101_G5_FoodieTime/commit/f7f6e787055d6ce48ea1ac581fc13ce246a93d56)
=> Finish Cart.html and CartController.java]

src/main/java/com/foodietime/post/controller/PostController.java, src/main/java/com/foodietime/postcategory/model/PostCategoryService.java, src/main/java/com/foodietime/postcategory/model/PostCategoryVO.java, src/main/resources/static/css/front/post/post.css, src/main/resources/static/css/front/post/style.css, src/main/resources/static/js/front/post/discuss.js, src/main/resources/static/js/front/post/post.js, src/main/resources/templates/front/post/listOnePost.html, src/main/resources/templates/front/post/listallpost.html, src/main/webapp/NewFile.html, src/main/webapp/allpost.html, src/main/webapp/listOnePosr.html, src/main/webapp/select_page.html
listallpost和listonepost對應的js和css
Fix :修正postcate的型別
=> Feat :新增listallpost主頁面、listonepost頁面

src/main/java/com/foodietime/gbprod/dto/GroupBuyingDisplayDTO.java, src/main/java/com/foodietime/gbprod/dto/ProductDetailDTO.java, src/main/java/com/foodietime/gbprod/service/GroupBuyingDisplayService.java, src/main/java/com/foodietime/gbprod/service/ProductDetailService.java, src/main/resources/templates/front/gb/gball.html, src/main/resources/templates/front/gb/gbindex.html, src/main/resources/templates/front/gb/product-detail.html
單價總價功能恢復運作,日期的修正,刪掉價格階梯,加入登入才能參加團購,gb/all篩選從低到高、最新團購案、最熱門團購案
=> feat:productDetail功能補全

src/main/resources/static/css/common/index.css, src/main/resources/templates/index.html
add member coupon and merchant orders
=> feat: change new index

src/main/java/com/foodietime/aspect/ExceptionAspect.java, src/main/java/com/foodietime/gbprod/controller/gbservlet.java, src/main/java/com/foodietime/gbprod/dto/GroupBuyingDisplayDTO.java, src/main/java/com/foodietime/gbprod/dto/JoinGroupRequest.java, src/main/java/com/foodietime/gbprod/dto/MemberInfoDTO.java, src/main/java/com/foodietime/gbprod/dto/ProductDetailDTO.java, src/main/java/com/foodietime/gbprod/dto/ReviewDTO.java, src/main/java/com/foodietime/gbprod/model/GbprodVO.java, src/main/java/com/foodietime/gbprod/service/GroupBuyingDisplayService.java, src/main/java/com/foodietime/gbprod/service/ProductDetailService.java, src/main/java/com/foodietime/gbprod/service/ReviewService.java, src/main/java/com/foodietime/groupbuyingcases/model/GroupBuyingCasesVO.java, src/main/java/com/foodietime/grouporders/model/GroupOrdersVO.java, src/main/resources/templates/front/gb/gball.html, src/main/resources/templates/front/gb/gbindex.html, src/main/resources/templates/front/gb/product-detail.html
網頁圖片改成url串接,可以透過JoinGroupRequestDTO,MemberInfo去將團購訂單的資訊新增、團購參與者新增、團購案的總數量更新進去
=> feat:修改團購網頁,可以新增團購訂單

pom.xml, src/main/java/com/foodietime/config/WebSocketConfig.java, src/main/java/com/foodietime/memcoupon/model/MemCouponService.java, src/main/java/com/foodietime/orders/controller/MemOrdersController.java, src/main/java/com/foodietime/orders/dto/OrderNotificationDTO.java, src/main/java/com/foodietime/orders/model/OrdersService.java, src/main/java/com/foodietime/orders/websocket/OrderNotificationWebSocket.java, src/main/java/com/foodietime/product/controller/ProductCategoryController.java, src/main/resources/static/js/front/merchantorders/merchant-orders.js, src/main/resources/templates/front/member/member_center.html, src/main/resources/templates/front/memberorders/member-orders.html, src/main/resources/templates/front/merchantorders/merchant-orders.html, src/main/resources/templates/front/restaurant/category.html, src/main/resources/templates/front/restaurant/chinese-cuisine.html
=> feat: 完成領取優惠券    feat: 完成會員頁檢視orders 

src/main/resources/templates/index.html
=> modify: 修改連結

src/main/java/com/foodietime/orders/controller/OrdersController.java, src/main/resources/static/css/front/cart/checkout.css, src/main/resources/static/js/front/cart/checkout.js, src/main/resources/templates/front/cart/checkout.html
=> modify: 結帳介面一鍵帶入地址

src/main/resources/static/js/front/cart/checkout.js, src/main/resources/templates/front/cart/checkout.html
修正使用優惠卷未滿最低金額時，送出訂單會導致頁面資料流失的bug
=> fix: 修正使用優惠卷未滿最低金額時，送出訂單會導致頁面資料流失的bug

pom.xml, src/main/resources/application.properties
修改application.properties跟pom.xml
=> modify: 修改application.properties跟pom.xml

src/main/java/com/foodietime/product/controller/ProductCategoryController.java, src/main/resources/static/css/front/restaurant/restaurant-categories.css, src/main/resources/templates/front/restaurant/category.html
修正優惠卷禁止領取的狀態跟提示登入的燈箱[取消]按鍵失效bug
=> fix: 修正優惠卷禁止領取的狀態跟提示登入的燈箱[取消]按鍵失效bug

src/main/java/com/foodietime/資料庫建立/DatabaseImageWriter.java
=> modify: 統一所有圖片寫進資撩庫

src/main/java/com/foodietime/util/ImageUtil.java
=> feat: 增加壓縮圖片的方法

pom.xml, src/main/java/com/foodietime/store/controller/StorePageController.java, src/main/java/com/foodietime/util/ImageUtil.java, src/main/java/com/foodietime/資料庫建立/DatabaseImageWriter.java
=> modify: 壓縮寫入資料庫的圖片大小

src/main/java/com/foodietime/post/controller/PostMController.java
=> modify: 修正衝突

src/main/java/com/foodietime/cart/controller/CartController.java, src/main/java/com/foodietime/cart/dto/CartItemDTO.java, src/main/java/com/foodietime/cart/model/CartService.java, src/main/java/com/foodietime/config/RedisConfig.java, src/main/java/com/foodietime/controller/GlobalControllerAdvice.java, src/main/java/com/foodietime/orders/controller/OrdersController.java, src/main/java/com/foodietime/orders/model/OrdersService.java, src/main/resources/application.properties, src/main/resources/static/js/front/cart/cart.js, src/main/resources/templates/front/cart/cart.html, src/main/resources/templates/front/cart/order-confirmation.html, src/main/resources/templates/front/merchantorders/merchant-orders.html
=> modify: 修改購物車model為Redis

src/main/resources/templates/front/merchantorders/merchant-orders.html, src/main/resources/templates/front/store/sc.html
=> modify: 優化商家畫面

src/main/resources/templates/index.html
=> modify: 調整首頁

src/main/resources/templates/admin/smg/admin-login.html, src/main/resources/templates/front/gb/payment-success.html
=> fix:修改付款檢視訂單
